from __future__ import annotations

import ast
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
README_PATH = ROOT / "README.md"
LOCAL_MODULES = {path.stem for path in ROOT.glob("*.py")}

SCRIPT_DESCRIPTIONS = {
    "main_pi_bios_v15.py": "Main live monitoring engine for EEG detection, patient state updates, and hardware alerts.",
    "train_and_export.py": "Training and incremental retraining pipeline that exports the scaler and models.",
    "dashboard_v2.py": "Streamlit dashboard for multi-patient monitoring, metrics, and history views.",
    "neurowatch_metrics.py": "Offline metrics pipeline for the prepared test dataset.",
    "run_prediction.py": "Local prediction and visualization utility for stepping through EEG files.",
    "patients.py": "Patient registry with live and demo patient definitions.",
    "sms_notifier.py": "Twilio-based SMS notification helper with cooldown handling.",
    "scan_edf_dataset.py": "Dataset scanning helper for EDF-based EEG files.",
}

PROJECT_SUMMARY = (
    "NeuroWatch is an EEG seizure detection and monitoring project that combines "
    "machine learning, a Raspberry Pi runtime, patient-state tracking, JSON feeds "
    "for a dashboard, and optional SMS alerts."
)

WATCHED_SUFFIXES = {".py", ".ps1", ".json", ".md"}
IGNORED_NAMES = {
    "README.md",
    "neurowatch_status.json",
    "neurowatch_patients.json",
    "neurowatch_metrics.json",
    "neurowatch_metrics_output.json",
}


def list_project_scripts() -> list[Path]:
    return sorted(ROOT.glob("*.py"))


def collect_imports(py_file: Path) -> set[str]:
    modules: set[str] = set()
    try:
        tree = ast.parse(py_file.read_text(encoding="utf-8", errors="ignore"))
    except SyntaxError:
        return modules

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                modules.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom) and node.module:
            modules.add(node.module.split(".")[0])
    return modules


def classify_dependencies(imports: set[str]) -> tuple[list[str], list[str]]:
    stdlib = {
        "argparse",
        "ast",
        "csv",
        "datetime",
        "glob",
        "json",
        "math",
        "os",
        "pathlib",
        "random",
        "runpy",
        "shutil",
        "subprocess",
        "sys",
        "threading",
        "time",
        "tkinter",
        "typing",
        "warnings",
    }
    optional = {"twilio", "RPi", "RPLCD", "PIL"}
    local_names = LOCAL_MODULES | {"src", "scripts"}
    third_party = sorted(
        name
        for name in imports
        if name not in stdlib
        and name not in optional
        and name not in local_names
        and name != "__future__"
    )
    optional_found = sorted(name for name in imports if name in optional)
    return third_party, optional_found


def find_data_sections() -> list[str]:
    data_root = ROOT / "data"
    if not data_root.exists():
        return []
    dirs = [path for path in data_root.iterdir() if path.is_dir()]
    return sorted(path.relative_to(ROOT).as_posix() for path in dirs)


def list_generated_outputs() -> list[str]:
    outputs = [
        "neurowatch_status.json",
        "neurowatch_patients.json",
        "neurowatch_metrics.json",
    ]
    history_files = sorted(path.name for path in ROOT.glob("neurowatch_history_*.json"))
    return outputs + history_files


def watched_files() -> list[str]:
    results: list[str] = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if path.name in IGNORED_NAMES:
            continue
        if path.suffix.lower() not in WATCHED_SUFFIXES:
            continue
        if "__pycache__" in path.parts:
            continue
        results.append(path.relative_to(ROOT).as_posix())
    return sorted(results)


def render_readme() -> str:
    scripts = list_project_scripts()
    imports: set[str] = set()
    for script in scripts:
        imports.update(collect_imports(script))

    core_deps, optional_deps = classify_dependencies(imports)
    data_sections = find_data_sections()
    outputs = list_generated_outputs()
    tracked_inputs = watched_files()
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines: list[str] = []
    lines.append("# NeuroWatch Project")
    lines.append("")
    lines.append("> This README is auto-generated by `generate_readme.py`.")
    lines.append(f"> Last generated: {generated_at}")
    lines.append("")
    lines.append(PROJECT_SUMMARY)
    lines.append("")
    lines.append("## Project Structure")
    lines.append("")
    lines.append("- `src/` — application code (monitor engine, dashboards, patient registry, notifier, metrics pipeline)")
    lines.append("- `scripts/` — utility scripts (training, prediction helper, dataset scanner, README generator)")
    lines.append("- `models/` — trained artifacts and training history")
    lines.append("- Root `.py` files — compatibility launchers so existing commands still work")
    lines.append("")
    lines.append("## How to Run")
    lines.append("")
    lines.append("1. Install dependencies:")
    lines.append("")
    lines.append("```bash")
    lines.append("pip install -r requirements.txt")
    lines.append("```")
    lines.append("")
    lines.append("2. (Optional) Configure Twilio SMS placeholders in `.env`.")
    lines.append("")
    lines.append("3. Start the core workflows:")
    lines.append("")
    lines.append("```bash")
    lines.append('python train_and_export.py --data "data/Bonn Univeristy Dataset"')
    lines.append("python main_pi_bios_v15.py")
    lines.append("streamlit run dashboard_v2.py")
    lines.append("```")
    lines.append("")
    lines.append("## What This Project Does")
    lines.append("")
    lines.append("- Detects EEG states as `Normal`, `Pre-Seizure`, or `Seizure`")
    lines.append("- Uses a hybrid `SVM + Random Forest` model")
    lines.append("- Monitors one live patient and can simulate demo patients for the dashboard")
    lines.append("- Writes JSON outputs for real-time UI updates")
    lines.append("- Supports optional Raspberry Pi GPIO, LCD, buzzer, and Twilio SMS alerts")
    lines.append("")
    lines.append("## Main Files")
    lines.append("")
    for script in scripts:
        desc = SCRIPT_DESCRIPTIONS.get(script.name, "Project utility script.")
        lines.append(f"- `{script.name}`: {desc}")
    lines.append("")
    lines.append("## Data Layout")
    lines.append("")
    if data_sections:
        for section in data_sections:
            lines.append(f"- `{section}/`")
    else:
        lines.append("- `data/` was not found when this README was generated.")
    lines.append("")
    lines.append("## Models")
    lines.append("")
    lines.append("- Export path: `models/`")
    lines.append("- Main artifacts: `scaler.pkl`, `svm_model.pkl`, `rf_model.pkl`")
    lines.append("- Incremental training artifacts: `training_archive.npz`, `training_history.json`")
    lines.append("")
    lines.append("## Dependencies")
    lines.append("")
    lines.append("Core packages detected from the Python scripts:")
    lines.append("")
    for dep in core_deps:
        lines.append(f"- `{dep}`")
    if optional_deps:
        lines.append("")
        lines.append("Optional integrations detected:")
        lines.append("")
        for dep in optional_deps:
            lines.append(f"- `{dep}`")
    lines.append("")
    lines.append("Suggested install command:")
    lines.append("")
    install_packages = [
        "joblib",
        "matplotlib",
        "mne",
        "numpy",
        "pandas",
        "plotly",
        "pyedflib",
        "scikit-learn",
        "scipy",
        "streamlit",
        "twilio",
    ]
    lines.append("```bash")
    lines.append(f"pip install {' '.join(install_packages)}")
    lines.append("```")
    lines.append("")
    lines.append("## Common Commands")
    lines.append("")
    lines.append("Train or refresh the models:")
    lines.append("")
    lines.append("```bash")
    lines.append('python train_and_export.py --data "data/Bonn Univeristy Dataset"')
    lines.append("```")
    lines.append("")
    lines.append("Run the monitoring engine:")
    lines.append("")
    lines.append("```bash")
    lines.append("python main_pi_bios_v15.py")
    lines.append("```")
    lines.append("")
    lines.append("Run the dashboard:")
    lines.append("")
    lines.append("```bash")
    lines.append("streamlit run dashboard_v2.py")
    lines.append("```")
    lines.append("")
    lines.append("Compute offline metrics:")
    lines.append("")
    lines.append("```bash")
    lines.append("python neurowatch_metrics.py")
    lines.append("```")
    lines.append("")
    lines.append("Regenerate this README manually:")
    lines.append("")
    lines.append("```bash")
    lines.append("python generate_readme.py")
    lines.append("```")
    lines.append("")
    lines.append("Start automatic README updates in PowerShell:")
    lines.append("")
    lines.append("```powershell")
    lines.append(".\\watch_readme.ps1")
    lines.append("```")
    lines.append("")
    lines.append("## Runtime Outputs")
    lines.append("")
    for output in outputs:
        lines.append(f"- `{output}`")
    lines.append("")
    lines.append("## Auto-Update Behavior")
    lines.append("")
    lines.append("The README can now be regenerated automatically by `watch_readme.ps1`.")
    lines.append("The watcher listens for changes in project files such as Python, PowerShell, JSON, and Markdown files, then reruns `generate_readme.py` after a short debounce delay.")
    lines.append("")
    lines.append("Files currently included in that watch scope:")
    lines.append("")
    for item in tracked_inputs:
        lines.append(f"- `{item}`")
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- The auto-generated README is best for keeping structure, scripts, and commands current.")
    lines.append("- It cannot infer every design decision or research note automatically, so you can still add manual project documentation elsewhere if you want richer narrative docs.")
    lines.append("- `sms_notifier.py` should use environment variables for secrets before sharing or deploying this project.")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    README_PATH.write_text(render_readme(), encoding="utf-8")
    print(f"README updated: {README_PATH}")


if __name__ == "__main__":
    main()
